baseurl = "https://manu.sridharan.net/blog"
languageCode = "en-us"
title = "Transitive Closure"
theme = "hyde"
[params]
  Description = "Manu Sridharan's research blog.  Posts are my own."
[[menu.main]]
  name = "Home page"
  url = "https://manu.sridharan.net"
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/rakingleaves"
[permalinks]
  posts = "/:year/:month/:day/:title/"
